## Production

This code should be running on server or in cloud

In [3]:
from pycaret.regression import *
import pandas as pd

In [4]:
# load the dataset from pycaret
from pycaret.datasets import get_data
dataset = get_data('diamond')

   Carat Weight    Cut Color Clarity Polish Symmetry Report  Price
0          1.10  Ideal     H     SI1     VG       EX    GIA   5169
1          0.83  Ideal     H     VS1     ID       ID   AGSL   3470
2          0.85  Ideal     H     SI1     EX       EX    GIA   3183
3          0.91  Ideal     E     SI1     VG       VG    GIA   4370
4          0.83  Ideal     G     SI1     EX       EX    GIA   3171

In [5]:
# new_data = pd.read_csv('diamond_new_data.csv', 
#                        header = 0,
#                        sep = ';')

data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)

data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

print('Data for Modeling: ' + str(data.shape))
print('Unseen Data For Predictions ' + str(data_unseen.shape))

Data for Modeling: (5400, 8)
Unseen Data For Predictions (600, 8)

In [6]:
data_unseen.head()

   Carat Weight        Cut Color Clarity Polish Symmetry Report  Price
0          1.53      Ideal     E     SI1     ID       ID   AGSL  12791
1          1.50       Fair     F     SI1     VG       VG    GIA  10450
2          1.01       Good     E     SI1      G        G    GIA   5161
3          2.51  Very Good     G     VS2     VG       VG    GIA  34361
4          1.01       Good     I     SI1     VG       VG    GIA   4238

In [7]:
saved_final_lightgbm = load_model('models/diamond-pipeline')

Transformation Pipeline and Model Successfully Loaded

In [8]:
new_prediction = predict_model(saved_final_lightgbm, data=data_unseen)

In [9]:
new_prediction.head()

,Carat Weight,Cut,Color,Clarity,Polish,Symmetry,Report,Price,prediction_label
0,1.53,Ideal,E,SI1,ID,ID,AGSL,12791,10166.494098
1,1.50,Fair,F,SI1,VG,VG,GIA,10450,9562.490920
2,1.01,Good,E,SI1,G,G,GIA,5161,4360.275460
3,2.51,Very Good,G,VS2,VG,VG,GIA,34361,30857.551363
4,1.01,Good,I,SI1,VG,VG,GIA,4238,3756.506116